server:
  port: 8000

spring:
  application:
    name: cloud-consumer-order8000
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    ## 时间格式
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8